services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "1800:8080"

  frontend-admin:
    build: ./frontend-admin
    restart: always
    ports:
      - "1890:80"
    depends_on:
      - backend

  frontend-user:
    build: ./frontend-user
    restart: always
    ports:
      - "1880:80"
    depends_on:
      - backend
