services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "1890:1890"
      - "1880:1880"
      - "1800:1800"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend-admin
      - frontend-user

  backend:
    build: ./backend
    restart: always

  frontend-admin:
    build: ./frontend-admin
    restart: always
    depends_on:
      - backend

  frontend-user:
    build: ./frontend-user
    restart: always
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
